# codegen.py
from typing import Dict, Any


def blueprint_to_python_code(bp: Dict[str, Any]) -> str:
    """
    Generate standalone Python code for the final agent.
    """
    name = bp.get("name", "EVA_Agent")
    bp_id = bp.get("id", "unknown")
    metadata = bp.get("metadata", {})
    generation = metadata.get("generation", 1)

    prompt_template = bp["prompt_templates"]["pt1"]
    temperature = bp.get("temperature", 0.2)
    max_tokens = bp.get("max_tokens", 300)

    code = f'''"""
Auto-generated EVA agent: {name}
Blueprint ID: {bp_id}
Generation: {generation}

This code was generated by EVA - The AI That Builds Other AIs.
"""

PROMPT_TEMPLATE = {prompt_template!r}
TEMPERATURE = {temperature}
MAX_TOKENS = {max_tokens}


def run_agent(text: str, llm_client):
    """Run this EVA-generated agent on the given input text."""
    prompt = PROMPT_TEMPLATE.replace("{{text}}", text)
    return llm_client(prompt, temperature=TEMPERATURE, max_tokens=MAX_TOKENS)
'''
    return code
S